### ISSUE TITLE
Remove lib mod

### ISSUE THREAD

**Issue by FedorBuggins** [FedorBuggins/insulin-bot#4]
To simplify project.

May be useful when create custom bin to handle errors or add other commands

**Comment by LitleStuart** [comment]
What does 'Remove lib mod' mean?

**Comment by FedorBuggins** [comment]
> What does 'Remove lib mod' mean?

Rust crate has complex structure. There are lib and several bins that uses this lib (shared code). It's nice to have separate lib for multiple different programs, scripts. But complexity is growing. Everything has cost.

**Comment by FedorBuggins** [comment]
See #10
